#!/bin/bash
# friscod daemon
# chkconfig: 2345 20 80
# description: FriskyTaphouse daemon
# processname: friscod

DAEMON_PATH="/var/www/friskytaphouse.com/frisco-backend/"
DAEMON=http_server.py
DAEMONOPTS=""

NAME=friscod
DESC="Frisky Taphouse Daemon"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/friscod

case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    
    cd $DAEMON_PATH
    PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
    #echo "Saving PID" $PID " to " $PIDFILE

    if [ -z $PID ]; then
        printf "%s\n" "Fail"
    else
        echo $PID > $PIDFILE
        printf "%s\n" "OK"
    fi
;;
status)
    printf "%-50s" "Checking $Name..."

    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`

        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
            printf "%s\n" "Process dead but pidfile exists"
        else
            echo "Running"
        fi
    else
        printf "%s\n" "Service not running"
    fi
;;
stop)
    printf "%-50s" "Stopping $NAME"

    PID=`cat $PIDFILE`
    cd $DAEMON_PATH

    if [ -f $PIDFILE ]; then
        kill -HUP $PID
        printf "%s\n" "OK"
        rm -f $PIDFILE
    else
        printf "%s\n" "pidfile not found"
    fi
;;
restart)
    $0 stop
    $0 start
;;
*)
    # Default case
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac

